version: "3.6"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  opentelemetry:
    image: otel/opentelemetry-collector:0.7.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./configs/opentelemetry.yaml:/etc/otel-agent-config.yaml
    links:
      - jaeger
    ports:
      - "55680:55680" # OTLP receiver

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    logging:
      driver: loki
      options:
        loki-url: http://loki

  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml

  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - "3000:3000"
