version: "3.6"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  opentelemetry:
    image: otel/opentelemetry-collector:0.4.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./configs/opentelemetry.yaml:/etc/otel-agent-config.yaml
    links:
      - jaeger
    ports:
      - "1777:1777"   # pprof extension
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "55678:55678" # OpenCensus receiver
      - "55680:55680" # OTLP receiver
      - "55679:55679" # zpages extension
      - "13133"       # health_check

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
